app:
  EXCLUDED_APIS:
  - path: /api/v1/login
    method: POST
  - path: /api/v1/register
    method: POST
  - path: /api/v1/logout
    method: POST
  - path: /api/v1/forgot-password
    method: POST
  - path: /api/v1/reset-password
    method: POST